services:
  react:
    container_name: portal_react
    image: portal_react
    hostname: reactportal
    build:
      context: .
      dockerfile: dist/Dockerfile
    ports:
      - "7050:7050"
    stdin_open: true
    logging:
      driver: "json-file"
    restart: always
    networks:
      - portal_network

  php:
    container_name: portal_php
    image: portal_php
    hostname: phpportal
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "9000:9000"
    logging:
      driver: "json-file"
    restart: always
    depends_on:
      - react
    networks:
      - portal_network

  nginx:
    container_name: portal_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
      - ./dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - php
      - react
    logging:
      driver: "json-file"
    networks:
      - portal_network

networks:
  portal_network:
    driver: bridge
